// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VeH7TfzWTxRL1LCK4aPcuLdZxZWVJRA',
    appId: '1:771057718470:web:5057be274bd969df9fb3c7',
    messagingSenderId: '771057718470',
    projectId: 'auth-email-password-fire-fe9da',
    authDomain: 'auth-email-password-fire-fe9da.firebaseapp.com',
    storageBucket: 'auth-email-password-fire-fe9da.appspot.com',
    measurementId: 'G-C0S975LRTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRW01CqBJQJX3H6JgqCWO_EoHvTUijhI',
    appId: '1:771057718470:android:0c79b17a38e426ab9fb3c7',
    messagingSenderId: '771057718470',
    projectId: 'auth-email-password-fire-fe9da',
    storageBucket: 'auth-email-password-fire-fe9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEN-nn1VkpKrRgC367JESnH8ssf-PFaw4',
    appId: '1:771057718470:ios:93277f805f1787109fb3c7',
    messagingSenderId: '771057718470',
    projectId: 'auth-email-password-fire-fe9da',
    storageBucket: 'auth-email-password-fire-fe9da.appspot.com',
    iosBundleId: 'com.example.authEmailPasswordFirebase',
  );
}
